# Generated by Django 5.1.5 on 2025-11-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='en_attente', max_length=50),
        ),
    ]
