# Generated by Django 5.2.8 on 2026-03-10 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorie_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement',
            new_name='cree_le',
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='modifie_le',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='note_admin',
            field=models.TextField(blank=True, help_text='Message affiché au fournisseur lors du refus'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fournisseurs/'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='products.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='products.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('message', 'Message admin'), ('validation', 'Statut validation'), ('commande', 'Nouvelle commande'), ('stock', 'Alerte stock'), ('info', 'Information')], default='info', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.fournisseur')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifs_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='ajoute_le',
        ),
    ]
